### ISSUE TITLE
[S] Working with Sequence Data

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2017#10]
- [x] Read Working with Sequence Data 339-354
- [x] What is the most useful / practical information gained from this reading?
- [x] What progress have you made since last week?
- [x] What are the primary challenges you are facing from an informatics perspective?

**Comment by SMay1** [comment]
From 'Working with Sequencing Data':

Most of this chapter was review for me. I have spent a lot of time (especially lately) dealing with fasta, fastq, sam, and bam files. The most useful bit was the section on indexing files, which I had never really done. This can be particularly useful for extremely large fasta/fastq files that are too big to open. 

Also, this chapter talks a bit about the importance of knowing when to write your own script/program and when to use a pre-established open source program. They air on the side of caution by saying that it is almost always better to use a pre-established program... That is good to keep in mind- I often shy away from using packages in R because they take more time to learn than writing my own scripts... However, I also shy away from writing scripts because they are more time consuming than just using excel... So, I find myself questioning some of my methods, which often involve calculating allele frequencies and the like manually in excel because it is easier to visualize... but I realize that this leaves a lot of room for error which I am not necessarily happy about.

**Comment by SMay1** [comment]
I was on vacation last week (hence the late response to this issue). This week has been mostly dedicated to genotyping my sequencing data, which is generating some interesting results. Today alone I found some cool results that might lead to a paper/chapter.  With the genotyping data I can calculate allele frequencies, compare GT-seq results to RAD results, and figure out which loci are amplifying the wrong things. Hopefully by next week I will be all done with optimizing round one and be able to move on to round two!

**Comment by SMay1** [comment]
From an informatics perspective, the thing that is most difficult is keeping track of all my data files and making use of them reproducibly.

I have so many folders withing folders of data and I am not sure what I should be saving to github and what I should be ignoring. It is hard to differentiate between 'results' and 'data' because they often look pretty much the same.

As I said above, I also have been doing a lot of work in excel, and I am not sure how kosher that is exactly.

I feel like a lot of what I am doing is extremely qualitative. I am trying to optimize my panel: to find primers that are misbehaving and either throw them out or redesign them... but there aren't a lot of quantitative cut-offs... it is mostly a lot of, "I don't feel like this looks 'right.'" and then doing that for 200+ loci one at a time with 10 different tests. It has become difficult to keep track of and my notes have fallen by the way-side because of it. I am not sure if that is because: 
1. I don't know what I am doing and am learning as I go
2. The nature of this analysis is qualitative so I am doing it as best I can
3. I am doing something critically wrong bioinformatically that would make all of this a lot easier

Probably some combination of the three... But, overall I think things are going really well, despite some digging in the dark/ general confusion
