### ISSUE TITLE
[L] Visualization

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2017#7]
@laurahspencer for this week

- [ ]  report on all the progress you made last week
- [ ]  provide some visualization of the most interesting aspect of your results
- [ ]  name what you find to be the most challenging aspect of the data analysis process.

**Comment by laurahspencer** [comment]
#### Progress:
- Made headway [drafting paper,](https://docs.google.com/a/uw.edu/document/d/1LEzRkAWbgG62Ju3qxKnpDVLUAPlknxGWsARVRzEzvMg/edit?usp=sharing) including more methods details, some introductory & discussion language
- SRM Analysis:
    * Re-ran SRM analysis using different (correct) Skyline settings, tested it using Woodpecker to inspect reproducibility
    * Quantified distance between technical replicates on NMDS plot, used to _quantitatively_ edit out unaligned tech reps. See [lab notebook post](https://laurahspencer.github.io/LabNotebook/Quantifying-tech-rep-validation/)
    * Addressed (most) reproducibility [issues](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/issues?q=is%3Aissue+is%3Aclosed) identified by other people  
- DIA Analysis:
    * Started drafting analysis workflow [notebooks](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/tree/master/notebooks/DIA) 

#### Visualizations:
  * Interactive Plotly plots: 
    - [NMDS of technical reps](https://plot.ly/~lhs3/3.embed)
    - [Distance between tech reps on NMDS](https://plot.ly/~lhs3/1.embed)
    - [SRM NMDS, points coded by site, treatment](https://plot.ly/~lhs3/5.embed)
  * Box plots showing expression by site, with ANOSIM stats:
    - [Protein Disulfide Isomerase](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/analyses/SRM/boxplot-PDI-site.png?raw=true)
    - [HSP70](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/analyses/SRM/boxplot-HSP70-site.png?raw=true)
    - [HSP90](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/analyses/SRM/boxplot-HSP90-site.png?raw=true) 


#### Difficulties so far: 
  * Reproducibility issues on different operating systems.
    - E.g. Sam using Ubuntu won't install R libraries
    - I want to include a couple steps use bash to make simple edits to fasta files, but since all other programs require Windows I should probably assume all steps will be executed on Windows.  
  * Linking to files when unsure how users will use notebooks
  * I'm a slow writer
  * Reconstructing DIA analysis workflow; disjointed due to multiple computers used, very large files = slow process, didn't use R to do analyses in March (used Excel); will need to write R scripts

**Comment by laurahspencer** [comment]
Calculated CV for my SRM data and visualized using Plotly. NOTE: The CV calculation includes data for all tech reps (in some cases I have up to 4), none removed.  My next step could be to remove poor-quality reps and regenerate this data. @yaaminiv I thought you'd like to check this out. 

[Plotly CV plot](https://plot.ly/~lhs3/7.embed). You can double click on a protein in the legend to only view data from that protein, and click through each protein separately, if desired.

**Comment by sr320** [comment]
interesting... Looks like 20 is decent number to go with given the spread here.
