### ISSUE TITLE
[S] Unix and Setup

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2017#8]
For this week 

- [x]  report on all the progress you made last week
- [x]  add some structure to you repo that reflects your current project
- [x]  Read Retrieving Bioinformatics Data 109-124, Unix Data tools 125-168 and provide what you think are the best new nuggets of information

**Comment by SMay1** [comment]
As for the progress I've made in the last week:

- Created a repo for my project
- Organized it (Data, Scripts, Programs, Notebooks)
- Figured out how to congruently run jupyter notebook on my VM and Desktop (extremely useful)
- Figured out how to make a .gitignore (Had to restart the repository adding the .gitignore before other files)
- Annotating previously un-annotated scripts
- Running through a pipeline with my sequencing data that is becoming much more clear as I go (slowly but surely)
- Keep expecting things to go horribly wrong, but they are going surprisingly well- my data looks much better than anticipated

**Comment by SMay1** [comment]
As for adding structure to my class repo that reflects my current project...

Would you like me to recreate the repo that I made for my project in the class repo? Or is what I've made sufficient even though it isn't linked to the class?

**Comment by sr320** [comment]
What you have is good - no reason to redo

**Comment by SMay1** [comment]
Readings:

Many of the unix commands in these chapters are things I have seen/used before but mostly shy away from. I find myself doing things in text editors because it is easier than learning command line one-liners. These chapters clarified that there are actually a choice few one-liners that make everything very easy and they can all feed into each other. 

Using these commands in Jupyter Notebook makes them even easier and reproducible and I will be using them more.

Things I have worked with pretty extensively already include:
- md5 checksums (dropbox corrupted a raw data file which drove me insane for about a week before I figured out how to use md5... although I should use it more regularly than I currently do)
- zipped files
- head/tail
-less

The rest of the commands I have had some exposure to but was not at all aware of the versatility of like grep, awk, and uniq... I am going to practice using them more instead of using text editors.

- I did not know about all the useful searching commands associated with -less, so that will be very helpful.

- Rsync is also a little obscure, but incredibly useful when needed

- Diff is also very useful and I did not know about it before the readings- I will probably use this frequently 

Not sure why wget or curl are any easier than just navigating to the webpage online and downloading the file in a GUI, so I had never used them before and don't really see myself using them
