### ISSUE TITLE
[Y] Finding the data

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2017#9]
For this week 

- [x]  report on all the progress you made last week
- [x]  create a new dataset with bad reps removed
- [x]  create a visualization of this new dataset that highlights the most interesting finding

**Comment by yaaminiv** [comment]
Last week:
Mainly focused on NSF, but helped Grace through some SRM protocol issues. I took note of a lot of her Skyline questions and I'm going to use them to make some sort of screencast, since I think that would be more helpful.

This week:
- **Made [PRTC NMDS](https://yaaminiv.github.io/Correlating-Technical-Replicates-Part4/)** at Emma's request ([script](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-PRTC-NMDS/2017-10-24-PRTC-NMDS.R)). Found that there was clustering based off of the order samples were run, possibly due to PRTC batches.
- **Focused on my technical replication troubleshooting plan**:
![53072576112__d17f7dce-7217-4b9c-9a88-50c852a6ea02](https://user-images.githubusercontent.com/22335838/32062874-9a02969a-ba2a-11e7-87b3-b073a81b35c2.JPG)
- **Coefficient of Variation filtering**: Used [new dataset](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Coefficient-of-Variation/2017-10-24-Norm-modSR.csv) to examine technical replication ([script](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Coefficient-of-Variation/2017-10-25-NMDS-for-Technical-Replication-after-CV-Filtering.R)) and cluster analysis ([script](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Coefficient-of-Variation/2017-10-25-NMDS-ANOSIM-for-Cluster-Analysis-after-CV-Filtering.R)). [Visualizations here](https://yaaminiv.github.io/Correlating-Technical-Replicates-Part5/). I found that my technical replication improved, but it's still not as good as it needs to be. NMDS/ANOSIM analyses are not significant. Perhaps there's just no difference in *C. gigas* after a month of outplant? The only possible difference I saw was with the Skokomish River group having ordinations farther away from the other four groups (that were all clustered together)
- **R-squared filtering**: Started NMDS/ANOSIM analyses for each cutoff ([script](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-10-Transition-Replicate-Correlations/2017-10-25-Cutoff-0.6/2017-10-25-NMDS-and-ANOSIM-Analysis-Cutoff-0.6.R))
- **Slope/Confidence Interval filtering**: Can't make a CI around a line with no error. I did add the slope of each regression line to my plots and found that the slope was generally close to 1 (.8-1.3) and there were large intercepts associated with each regression. [Visualizations here](https://yaaminiv.github.io/Correlating-Technical-Replicates-Part3/).
